# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArhatSwfitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArhatSwfitDemo
  pod 'Arhat', :path => '../' 

end

target 'ArhatSwiftDylibTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArhatSwiftDylibTest

  target 'ArhatSwiftDylibTestTests' do
    # Pods for testing
  end

end
